---
title: "Nutrition"
author: "Alexandra Norris"
date: "7/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(rstanarm)
library(sjPlot)
library(BalanceCheck)
library(cobalt)
library(arsenal)
library(gt)
```

```{r}

# read in data from Life in Australia Wave 4

data <- read_dta("aus.dta")

# select the data relevant to the nutrition experiment.  Filter for only online
# respondents (Mode ==1). I also create a treatment variable using the DUM1
# variable with 0 indicating the basic message and 1 indicating the nudge
# explanation

clean <- data %>%
  select(Mode, DUM1, DUM2a, DUM2b, DUM3a, DUM3b, D1, D2, D3, D4a, D4b, D4c, D4d, D4e, D4f, D4g) %>%
  mutate(treat = ifelse(is.na(DUM1), 0, 1))

# for balance we need the other variables

bal <- data %>%
  mutate(treat = ifelse(is.na(DUM1), 0, 1)) %>%
  select(treat, p_state, p_region, p_geography, p_seifa, p_gender, p_age_group, d_cob_group,  p_citizen, p_lote, p_atsi, p_household_str, d_education, weight)

try <- data %>%
  mutate(treat = ifelse(is.na(DUM1), "Control", "Transparency Message")) %>%
  select(treat, p_state, p_region, p_geography, p_seifa, p_gender, p_age_group, d_cob_group,  p_citizen, p_lote, p_atsi, p_household_str, d_education, weight)
 

mycontrols  <- tableby.control(test=FALSE, total=FALSE,
                               numeric.test="kwt", cat.test="chisq",
                               numeric.stats=c("N", "median", "q1q3"),
                               cat.stats=c("countpct"),
                               stats.labels=list(N='Count', median='Median', q1q3='Q1,Q3'))

table_1 <- tableby(treat ~ ., data = try)

balance_fit <- glm(treat ~ ., data = bal)

print(balance_fit)



summary(table_1, title = "Balance Check for DUM1")





```

```{r Descriptive Statistics}
# Generating ATT weights as specified in Austin (2011)
bal$p.score <- glm(f.build("treat", bal), data = bal, 
                       family = "binomial")$fitted.values
bal$att.weights <- with(bal, treat + (1-treat)*p.score/(1-p.score))

bal.tab(treat ~ p_state + p_region + p_geography + p_seifa + p_gender + p_age_group + d_cob_group + p_citizen + p_lote + p_atsi + p_household_str + d_education + weight, data = bal, weights = "att.weights", distance = "p.score")

```

```{r}
# Assessment of views about nudge approach versus traditional approach

# total responses to D1

a <- clean %>%
  select(D1) %>%
  count() 

# Number of respondents that support nudging (D1 = 1)

b <- clean %>%
  select(D1) %>%
  count(D1 == 1) %>%
  slice(2) %>%
  select(n)

# Number of respondents that so not support nudging (D1 = 2)

c <- clean %>%
  select(D1) %>%
  count(D1 == 2) %>%
  slice(2) %>%
  select(n)

# Number of respondents that didn't know or refused (D1 = -98 or -99)

d <- clean %>%
  select(D1) %>%
  filter(D1 %in% c(-98, -99)) %>%
  count()

```
```{r}
# online responses
# total responses to D1

clean %>%
  filter(Mode == 1) %>%
  select(D1) %>%
  count() 

# Number of respondents that support nudging (D1 = 1)

clean %>%
  filter(Mode == 1) %>%
  select(D1) %>%
  count(D1 == 1) %>%
  slice(2) %>%
  select(n)

# Number of respondents that so not support nudging (D1 = 2)

clean %>%
  filter(Mode == 1) %>%
  select(D1) %>%
  count(D1 == 2) %>%
  slice(2) %>%
  select(n)

# Number of respondents that didn't know or refused (D1 = -98 or -99)

clean %>%
  filter(Mode == 1) %>%
  select(D1) %>%
  filter(D1 %in% c(-98, -99)) %>%
  count()
```
```{r}
# Phone responses

# total responses to D1

clean %>%
  filter(Mode == 2) %>%
  select(D1) %>%
  count() 

# Number of respondents that support nudging (D1 = 1)

clean %>%
  filter(Mode == 2) %>%
  select(D1) %>%
  count(D1 == 1) %>%
  slice(2) %>%
  select(n)

# Number of respondents that so not support nudging (D1 = 2)

clean %>%
  filter(Mode == 2) %>%
  select(D1) %>%
  count(D1 == 2) %>%
  slice(2) %>%
  select(n)

# Number of respondents that didn't know or refused (D1 = -98 or -99)

clean %>%
  filter(Mode == 2) %>%
  select(D1) %>%
  filter(D1 %in% c(-98, -99)) %>%
  count()

```

```{r D2}
# Reasons people oppose government action - TOTAL

# remove the NA values
clean %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 1) 

clean %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 2) 

clean %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 3) 

clean %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 4) 

clean %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 5) 

# ONLINE ONLY

# Reasons people oppose government action

# remove the NA values
clean %>%
  filter(Mode == 1) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 1) 

clean %>%
  filter(Mode == 1) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 2) 

clean %>%
  filter(Mode == 1) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 3) 

clean %>%
  filter(Mode == 1) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 4) 

clean %>%
  filter(Mode == 1) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 5) 

# PHONE ONLY

clean %>%
  filter(Mode == 2) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 1) 

clean %>%
  filter(Mode == 2) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 2) 

clean %>%
  filter(Mode == 2) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 3) 

clean %>%
  filter(Mode == 2) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 4) 

clean %>%
  filter(Mode == 2) %>%
  select(D2) %>%
  na.omit() %>%
  count(D2 == 5) 

  
```
```{r D3}
# Ban versus nudge

# All responses

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count()

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count(D3 == 1)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count(D3 == 2)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count(D3 == 3)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count(D3 == 4)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  count(D3 == 5)

# TREAT = 0, non-transparency message
clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count()

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count(D3 == 1)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count(D3 == 2)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count(D3 == 3)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count(D3 == 4)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 0) %>%
  count(D3 == 5)

# Transparency message, treat = 1
clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count()

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count(D3 == 1)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count(D3 == 2)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count(D3 == 3)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count(D3 == 4)

clean %>%
  select(treat, D3) %>%
  na.omit() %>%
  filter(treat == 1) %>%
  count(D3 == 5)

```

```{r}
# regression analysis of D3 FULL SAMPLE

# filter out -98 and -99 because they will throw off the regression.  I also
# adjust the mode so the intercept represents an actual situation

new <- clean %>%
  filter(D3 %in% c(1,2,3,4,5)) %>%
  mutate(Mode_adj = Mode - 1) 

fit_1 <- lm(D3 ~ treat + Mode_adj, data = new)
print(fit_1)


# create table with regression output

tab_model(fit_1, show.se = FALSE, show.ci = 0.95, show.r2 = TRUE, show.p = TRUE, bpe = "median", collapse.se = FALSE, title = "Full Sample: Support for Menu Change Over Ban", dv.labels = "Support for Nudging over a Ban (Higher number indicates more support for nudge)", pred.labels = c("(Intercept)","Transparency Message", "Mode of Survey"))
```

```{r}
# Regression analysis of D3 PHONE ONLY

phone <- clean %>%
  filter(D3 %in% c(1,2,3,4,5)) %>%
  mutate(Mode_adj = Mode - 1)  %>%
  filter(Mode_adj == 1)

fit_2 <- lm(D3 ~ treat, data = phone)
print(fit_2)


# create table with regression output

tab_model(fit_2, show.se = FALSE, show.ci = 0.95, show.r2 = TRUE, show.p = TRUE, bpe = "median", collapse.se = FALSE, title = "Phone Only: Support for Menu Change Over Ban", dv.labels = "Support for Nudging over a Ban (Higher number indicates more support for nudge)", pred.labels = c("(Intercept)","Transparency Message"))

```
```{r}
# Regression analysis of D3 ONLINE ONLY

online <- clean %>%
  filter(D3 %in% c(1,2,3,4,5)) %>%
  mutate(Mode_adj = Mode - 1)  %>%
  filter(Mode_adj == 0)

fit_3 <- lm(D3 ~ treat, data = online)
print(fit_3)


# create table with regression output

tab_model(fit_3, show.se = FALSE, show.ci = 0.95, show.r2 = TRUE, show.p = TRUE, bpe = "median", collapse.se = FALSE, title = "Online Only: Support for Menu Change Over Ban", dv.labels = "Support for Nudging over a Ban (Higher number indicates more support for nudge)", pred.labels = c("(Intercept)","Transparency Message"))
```






























